name: WeatherRestrictions
main: de.crannk.xPaw.RandomWeather
version: 1.5
description: Configurable semi-random weather
author: xPaw & Tux2
commands:
   rain:
      description: Makes it rain in the current world (if enabled).
      usage: |
       /rain <world>
   rainclear:
      description: Stops all weather in the current world.
      usage: |
       /rainclear <world>
   clearrain:
      description: Stops all weather in the current world.
      usage: |
       /clearrain <world>
   thunder:
      description: Starts a lightning storm (independent of weather, and if enabled).
      usage: |
       /thunder <world>
   weatherstats:
      description: Gives you information on the current storm status in all worlds.
      usage: |
       /weatherstats
   lightning:
      description: Strikes a random location within 20 blocks of you
      usage: |
       /lightning
   wr:
      description: long, alternate constructor for commands
      usage: |
       /wr rain [world] - Make it rain
       /wr clear [world] - clear all the weather
       /wr thunder [world] - add thunder to the current storm
       /wr lightning - send a lightning bolt near you
       /wr stats - gives you the current weather in all your worlds